# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

thinCloud <- function(las, voxel = 0.025) {
    .Call(`_TreeLS_thinCloud`, las, voxel)
}

RCropCloud <- function(las, xCenter, yCenter, len, circle, negative) {
    .Call(`_TreeLS_RCropCloud`, las, xCenter, yCenter, len, circle, negative)
}

getHoughCircle <- function(las, pixel = 0.05, rad_max = 0.25, min_den = 0.1, min_votes = 3L) {
    .Call(`_TreeLS_getHoughCircle`, las, pixel, rad_max, min_den, min_votes)
}

singleStack <- function(las, pixel = 0.05, rad_max = 0.25, min_den = 0.1, min_votes = 3L) {
    .Call(`_TreeLS_singleStack`, las, pixel, rad_max, min_den, min_votes)
}

stackMap <- function(las, hmin = 1, hmax = 3, hstep = 0.5, pixel = 0.025, rad_max = 0.25, min_den = 0.1, min_votes = 3L) {
    .Call(`_TreeLS_stackMap`, las, hmin, hmax, hstep, pixel, rad_max, min_den, min_votes)
}

houghStemPoints <- function(las, h1 = 1, h2 = 3, hstep = 0.5, radius = 0.25, pixel = 0.025, density = 0.1, votes = 3L) {
    .Call(`_TreeLS_houghStemPoints`, las, h1, h2, hstep, radius, pixel, density, votes)
}

houghStemPlot <- function(las, ptIds, h1 = 1, h2 = 3, hstep = 0.5, radius = 0.25, pixel = 0.025, density = 0.1, votes = 3L) {
    .Call(`_TreeLS_houghStemPlot`, las, ptIds, h1, h2, hstep, radius, pixel, density, votes)
}

getCircleRansac <- function(las, nSamples = 5L, pConfidence = 0.99, pInliers = 0.8) {
    .Call(`_TreeLS_getCircleRansac`, las, nSamples, pConfidence, pInliers)
}

ransacStemCircle <- function(las, segs, rads, nSamples = 5L, pConfidence = 0.99, pInliers = 0.8, tolerance = 0.05) {
    .Call(`_TreeLS_ransacStemCircle`, las, segs, rads, nSamples, pConfidence, pInliers, tolerance)
}

irlsStemCylinder <- function(las, segs, rads, nPoints = 500L, tolerance = 0.05) {
    .Call(`_TreeLS_irlsStemCylinder`, las, segs, rads, nPoints, tolerance)
}

irlsStemCircle <- function(las, segs, rads, nSamples = 500L, tolerance = 0.05) {
    .Call(`_TreeLS_irlsStemCircle`, las, segs, rads, nSamples, tolerance)
}

ransacStemCylinder <- function(las, segs, rads, nSamples = 10L, pConfidence = 0.95, pInliers = 0.8, tolerance = 0.05) {
    .Call(`_TreeLS_ransacStemCylinder`, las, segs, rads, nSamples, pConfidence, pInliers, tolerance)
}

ransacPlotCircles <- function(las, tId, segs, rads, nSamples = 5L, pConfidence = 0.99, pInliers = 0.8, tolerance = 0.05) {
    .Call(`_TreeLS_ransacPlotCircles`, las, tId, segs, rads, nSamples, pConfidence, pInliers, tolerance)
}

ransacPlotCylinders <- function(las, tId, segs, rads, nSamples, pConfidence, pInliers, tolerance) {
    .Call(`_TreeLS_ransacPlotCylinders`, las, tId, segs, rads, nSamples, pConfidence, pInliers, tolerance)
}

irlsPlotCylinders <- function(las, tId, segs, rads, nPoints, tolerance) {
    .Call(`_TreeLS_irlsPlotCylinders`, las, tId, segs, rads, nPoints, tolerance)
}

irlsPlotCircles <- function(las, tId, segs, rads, nPoints, tolerance) {
    .Call(`_TreeLS_irlsPlotCircles`, las, tId, segs, rads, nPoints, tolerance)
}

pointMetricsCpp <- function(las, kIds, whichMetrics) {
    .Call(`_TreeLS_pointMetricsCpp`, las, kIds, whichMetrics)
}

voxelIndex <- function(las, d) {
    .Call(`_TreeLS_voxelIndex`, las, d)
}

voxelMetrics <- function(las, voxelIds, whichMetrics) {
    .Call(`_TreeLS_voxelMetrics`, las, voxelIds, whichMetrics)
}

treeEigenHough <- function(las, ids, split_by, voxel = 0.05, rad = 0.25, is2d = FALSE, getSpace = FALSE) {
    .Call(`_TreeLS_treeEigenHough`, las, ids, split_by, voxel, rad, is2d, getSpace)
}

plotEigenHough <- function(las, ids, split_by, resplit_by, voxel = 0.05, rad = 0.25, is2d = FALSE, getSpace = FALSE) {
    .Call(`_TreeLS_plotEigenHough`, las, ids, split_by, resplit_by, voxel, rad, is2d, getSpace)
}

cppFastApply <- function(matrix, funcList) {
    .Call(`_TreeLS_cppFastApply`, matrix, funcList)
}

cppCircleFit <- function(las, method = "qr", n = 5L, p = 0.99, inliers = 0.8, nbest = 0L) {
    .Call(`_TreeLS_cppCircleFit`, las, method, n, p, inliers, nbest)
}

cppCylinderFit <- function(las, method = "nm", n = 10L, p = 0.95, inliers = 0.9, max_angle = 30, n_best = 20L) {
    .Call(`_TreeLS_cppCylinderFit`, las, method, n, p, inliers, max_angle, n_best)
}

treeIdsFromMap <- function(las, xycenters, uniqueIds, length, circle) {
    .Call(`_TreeLS_treeIdsFromMap`, las, xycenters, uniqueIds, length, circle)
}

bruteForceRansacCylinder <- function(las, nSamples, pConfidence, pInliers, nBest, maxAngle) {
    .Call(`_TreeLS_bruteForceRansacCylinder`, las, nSamples, pConfidence, pInliers, nBest, maxAngle)
}

bfStemCylinder <- function(las, segs, rads, nSamples = 10L, pConfidence = 0.95, pInliers = 0.8, max_angle = 30, tolerance = 0.05) {
    .Call(`_TreeLS_bfStemCylinder`, las, segs, rads, nSamples, pConfidence, pInliers, max_angle, tolerance)
}

bfPlotCylinders <- function(las, tId, segs, rads, nSamples = 10L, pConfidence = 0.95, pInliers = 0.8, max_angle = 30, tolerance = 0.05) {
    .Call(`_TreeLS_bfPlotCylinders`, las, tId, segs, rads, nSamples, pConfidence, pInliers, max_angle, tolerance)
}

